In [6]:
import numpy as np, random, copy, time
n=int(input("enter size"))
a=np.zeros((n,n))
x=True
k,c=int(n/2),0
a[0][k]=2

def isopen(y,z):
    if y!=(n-1) and a[y+1][z]==1:
        y+=1
        a[y][z]=a[0][k]
        copy.deepcopy(isopen(y,z))
    if z!=(n-1) and a[y][z+1]==1:
        z+=1
        a[y][z]=a[0][k]
        copy.deepcopy(isopen(y,z))
    if a[y][z-1]==1 and z>=0:
        z-=1
        a[y][z]=a[0][k]
        copy.deepcopy(isopen(y,z))
    if a[y-1][z]==1 and y>=0:
        y-=1
        a[y][z]=a[0][k]
        copy.deepcopy(isopen(y,z))
start_time = time.time()
while x:
  i=random.randint(0,n-1)
  j=random.randint(0,n-1)
  if a[i][j]==0:
    a[i][j]=1
    c+=1
    h=copy.copy(a)
    for b in range(0,n):
        if a[0][b]==1:
            isopen(0,b)
            q=b
    if a[n-1][b]==a[0][k]:
      print(a)
      print("connected, count:",c,"Percentage:",(c/n),"time taken:",time.time() - start_time)
      x=False
    else:
      a=h

enter size100
[[0. 2. 0. ... 2. 2. 0.]
 [0. 0. 0. ... 2. 0. 2.]
 [0. 1. 0. ... 0. 2. 2.]
 ...
 [0. 0. 1. ... 0. 1. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 2. 1. ... 2. 2. 2.]]
connected, count: 5710 Percentage: 57.1 time taken: 2.208437204360962
